import os
import yaml

# load device configuration
configfile: "config/config.yaml"
PROJECT = config["project"]
DEVICE  = config.get("device", "local")
INDIR   = config['setup'][DEVICE]['input']
WD      = config['setup'][DEVICE]['output']
RESOURCES_DIR  = config["resources"]

# set up directories on device
PROJDIR        = os.path.join(WD, PROJECT)
PROCESSING_DIR = os.path.join(PROJDIR, "processing")
TRAINING_DIR   = os.path.join(PROJDIR, "training")
GENERATED_DIR  = os.path.join(PROJDIR, "generated")
FIGURE_DIR     = os.path.join(PROJDIR, "figures")
for directory in [PROJDIR, PROCESSING_DIR, TRAINING_DIR, GENERATED_DIR, FIGURE_DIR]:
    os.makedirs(directory, exist_ok=True)

# choose device-specific conda environments
PYENV = config['setup'][DEVICE]['pyenv']
RENV  = config['setup'][DEVICE]['renv']
RSUBDIR = config['setup'][DEVICE]['rsubdir']

# load project-specific configuration
configfile: f"config/projects/{PROJECT}.yaml"

YEAR0      = config["year0"]
YEARN      = config["yearn"]
FIELDS     = config["fields"]
RESOLUTION = config["resolution"]
LONGITUDE  = config["longitude"]
LATITUDE   = config["latitude"]
RFUNC      = config["rfunc"]
SFUNC      = config["sfunc"]
YEARS      = list(range(YEAR0, YEARN))
MTHRESH    = config["marginal_threshold"]

# load rules
include: "rules/get_data.smk"
include: "rules/process_data.smk"
include: "rules/visuals.smk"
