import os
import yaml
import glob

# load device configuration
configfile: "config/config.yaml"
PROJECT = config.get("project", "prototype")
# DEVICE  = config.get("device", "local")
DEVICE  = config["device"]
INDIR   = config['setup'][DEVICE]['input']
WD      = config['setup'][DEVICE]['output']
RESOURCES_DIR  = config["resources"]

# set up directories on device
PROJDIR        = os.path.join(WD, PROJECT)
PROCESSING_DIR = os.path.join(PROJDIR, "processing")
TRAINING_DIR   = os.path.join(PROJDIR, "training")
GENERATED_DIR  = os.path.join(PROJDIR, "generated")
FIGURE_DIR     = os.path.join(PROJDIR, "figures")
for newdir in [PROJDIR, PROCESSING_DIR, TRAINING_DIR, GENERATED_DIR, FIGURE_DIR]:
    os.makedirs(newdir, exist_ok=True)

# choose device-specific conda environments
GEOENV = config['setup'][DEVICE]['geoenv']
RENV  = config['setup'][DEVICE]['renv']
GPUENV = config['setup'][DEVICE]['gpuenv']
RSUBDIR = config['setup'][DEVICE]['rsubdir']

# load project-specific configuration
configfile: f"config/projects/{PROJECT}.yaml"

DATASET    = config["dataset"]
INDIR      = INDIR[DATASET]

YEAR0      = config["year0"]
YEARN      = config["yearn"]
FIELDS     = config["fields"]
RESOLUTION = config["resolution"]
LONGITUDE  = config["longitude"]
LATITUDE   = config["latitude"]
RFUNC      = config["rfunc"]
SFUNC      = config["sfunc"]
YEARS      = list(range(YEAR0, YEARN))
TIMECOL    = config['setup'][DEVICE]["timecol"]
MTHRESH    = config["marginal_threshold"]
KIMG       = config["kimg"]

# load rules
include: "rules/get_data.smk"
include: "rules/process_data.smk"
include: "rules/visuals.smk"
include: "rules/stylegan.smk"

# run full workflow (up to checkpoint)
rule all:
    """Complete full data processing sequence."""
    input:
        os.path.join(TRAINING_DIR, "images.zip"),
        os.path.join(FIGURE_DIR, "f01a.png"),
        os.path.join(FIGURE_DIR, "f01b.png"),
        os.path.join(FIGURE_DIR, "f01c.png")