# year range
year0: 2020 # 1940
yearn: 2021 #2023

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude:
  min: 10.0
  max: 25.0

# resolution
resolution:
  lon: 64
  lat: 64

# event threshold
event_threshold:
  field: ws
  value: 15
  func: max

# output fields
fields:
  ws:
    args:
      - u10
      - v10
    func: wind_speed
    agg: max
  msl:
    args:
      - msl
    func: identity
    agg: min
  tp:
    args:
      - tp
    func: identity
    agg: sum

rfunc:
  args:
    - ws
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

sfunc: additive 