dataset: imdaa

# year range (1940 to 2023)
year0: 1979
yearn: 2023

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude:
  min: 10.0
  max: 25.0

# resolution
resolution:
  lon: 64
  lat: 64

sfunc: additive

rfunc:
  args:
    - ws
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

# event threshold 
event_subset:
  field: ws
  value: 25.5
  func: max

# marginal threshold (for POT)
marginal_threshold: 0.95

# training probability space
domain: gumbel # gumbel, uniform

kimg: 300

# output fields
# TODO: add units
# TODO: add cmaps
# TODO: add titles
fields:
  ws:
    args:
      - GUST_10m
    func: identity
    hfunc: max
    obj: max
    distn: weibull
  msl:
    args:
      - PRMSL_msl
    func: identity
    hfunc: min
    obj: min
    distn: genpareto
  tp:
    args:
      - APCP_sfc
    func: identity
    hfunc: sum
    obj: max
    distn: genpareto
