dataset: imdaa

# year range (1940 to 2023)
year0: 1979
yearn: 2023

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude:
  min: 10.0
  max: 25.0

# resolution
resolution:
  lon: 64
  lat: 64

sfunc: additive

rfunc:
  args:
    - ws
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

# event threshold 
event_subset:
  field: ws
  value: 25.5
  func: max

# marginal threshold (for POT)
marginal_threshold: 0.95

# training probability space
domain: gumbel # gumbel, uniform

kimg: 40 #300

# output fields
fields:
  ws:
    args:
      - GUST_10m
    func: identity
    hfunc: max
    obj: max
    distn: weibull
    units: "mps"
    cmap: "viridis"
    title: "Wind Speed"
  msl:
    args:
      - PRMSL_msl
    func: identity
    hfunc: min
    obj: min
    distn: genpareto
    units: "Pa"
    cmap: "YlOrRd"
    title: "Mean Sea Level Pressure"
  tp:
    args:
      - APCP_sfc
    func: identity
    hfunc: sum
    obj: max
    distn: genpareto
    units: "mm" # same as kg p m-2
    cmap: "PuBu"
    title: "Total Precipitation"

points_of_interest:
  - bangladesh:
      - chittagong:
          lon: 91.8466
          lat: 22.3569
      - dhaka:
          lon: 90.4125
          lat: 23.8103
  - noaa_buoys:
      - buoy_23223:
          lon: 89.483
          lat: 17.333
      - buoy_23218:
          lon: 88.5
          lat: 10.165
      - buoy_23008:
          lon: 90.0
          lat: 12.0
      - buoy_23007:
          lon: 90.0
          lat: 8.0

# observation_points = {
#     # ----bangladesh----
#     'chittagong': (91.8466, 22.3569),
#     'dhaka': (90.4125, 23.8103),
#     # 'khulna': (89.5911, 22.8456),
#     # ----myanmar----
#     # 'sittwe': (92.9000, 20.1500),
#     # 'rangoon': (96.1561, 16.8409),
#     # ----india----
#     # 'kolkata': (88.3639, 22.5726),
#     # 'madras': (80.2707, 13.0827),
#     # 'vishakapatham': (83.3165, 17.6868),
#     # 'haldia': (87.9634, 22.0253),
#     # ----noaa buoys----
#     'buoy_23223': (89.483, 17.333),
#     # 'buoy_23219': (88.998, 13.472),
#     'buoy_23218': (88.5, 10.165),
#     # 'buoy_23009': (90.0, 15.0),
#     'buoy_23008': (90.0, 12.0),
#     'buoy_23007': (90.0, 8.0)
# }
