# year range (1940 to 2023)
year0: 2015
yearn: 2021

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude:
  min: 10.0
  max: 25.0

# resolution
resolution:
  lon: 64
  lat: 64

# event threshold
event_threshold:
  field: ws
  value: 15
  func: max

# marginal threshold
marginal_threshold:
  low: 0.6
  final: 0.95

# output fields
fields:
  ws:
    args:
      - u10
      - v10
    func: wind_speed
    hfunc: max
    obj: max
    distn: weibull
  msl:
    args:
      - msl
    func: identity
    hfunc: min
    obj: min
    distn: genpareto
  tp:
    args:
      - tp
    func: identity
    hfunc: sum
    obj: max
    distn: genpareto

rfunc:
  args:
    - ws
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

sfunc: additive 