dataset: imdaa

# year range (1940 to 2023) 
year0: 2020
yearn: 2021

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude: 
  min: 10.0
  max: 25.0

# resolution
resolution:
  lon: 128 #8 
  lat: 128 #8 

sfunc: additive

rfunc:
  args:
    - ws
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

# event threshold 
event_subset:
  field: ws
  value: 0
  func: max

# marginal threshold (for POT)
marginal_threshold: 0.6

# training probability space
domain: gumbel # gumbel, uniform

kimg: 250

# output fields
fields:
  ws:
    args:
      - GUST_10m
    func: identity
    hfunc: max
    obj: max
    distn: weibull
  msl:
    args:
      - PRMSL_msl
    func: identity
    hfunc: min
    obj: min
    distn: genpareto
  tp:
    args:
      - APCP_sfc
    func: identity
    hfunc: sum
    obj: max
    distn: genpareto