# year range
year0: 1940
yearn: 2025

# geographical boundaries
longitude:
  min: -11.0
  max: 2.0
latitude:
  min: 49.0
  max: 60.0

# resolution---check if nonstandard allowed in StyleGAN2
resolution:
  lon: 28 # 53
  lat: 28 # 45
 
# output fields
fields:
  v:
    args:
      - u10
      - v10
    func: wind_power
    hfunc: sum
    obj: min
    distn: genpareto
  g:
    args:
      - t2m
      - ssrd
      - u10
      - v10
    func: solar_power
    hfunc: sum
    obj: min
    distn: genpareto
  t2m:
    args:
      - t2m
    func: identity
    hfunc: mean
    obj: min
    distn: genpareto # exponential (not implemented yet)

rfunc:
  args:
    - v
    - g
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

sfunc: additive 
