# year range
year0: 1940
yearn: 2023

# geographical boundaries
longitude:
  min: -8.0
  max: 2.0
latitude:
  min: 49.0
  max: 60.0

# fields
fields:
  u10: "max"
  v10: "max"
  msl: "min"
  tp: "sum30"

field_names:
  u10: "10m_u_component_of_wind"
  v10: "10m_v_component_of_wind"
  msl: "mean_sea_level_pressure"
  tp: "total_precipitation"