dataset: imdaa

# year range (1940 to 2023)
year0: 1979
yearn: 2023

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude:
  min: 10.0
  max: 25.0

# resolution
resolution:
  lon: 64
  lat: 64

sfunc: additive # in r_utils/sfuncs.R

rfunc: # in r_utils/rfuncs.R
  args:
    - ws
  func: max # https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match.fun

# event threshold 
event_subset:
  field: ws
  value: 25.5
  func: max

# marginal threshold (for POT)
marginal_threshold: 0.95

# training probability space
domain: gumbel # gumbel, uniform

kimg: 600

# output fields
fields:
  ws:
    args:
      - GUST_10m
    func: identity # defined in py_utils/funcs.py
    hfunc: max # must be xarray compatible
    obj: max
    distn: weibull
    units: "mps"
    cmap: "viridis"
    title: "Wind Speed"
  msl:
    args:
      - PRMSL_msl
    func: identity
    hfunc: min
    obj: min
    distn: genpareto
    units: "Pa"
    cmap: "YlOrRd"
    title: "Mean Sea Level Pressure"
  tp:
    args:
      - APCP_sfc
    func: identity
    hfunc: sum
    obj: max
    distn: genpareto
    units: "mm" # same as kg p m-2
    cmap: "PuBu"
    title: "Total Precipitation"

points_of_interest: # (lon, lat)
  # bangladesh
  chittagong:
    - 91.8466
    - 22.3569
  dhaka:
    - 90.4125
    - 23.8103
  # noaa_buoys
  buoy_23223:
    - 89.483
    - 17.333
  buoy_23218:
    - 88.5
    - 10.165
  buoy_23008:
    - 90.0
    - 12.0
  buoy_23007:
    - 90.0
    - 8.0

