# Global config file
project: poweruk_winter
conda-cleanup-envs: true
conda-cleanup-pkgs: cache
conda-prefix: "conda"

# environment specs 
envs:
  apple-silicon:
    geoenv: '../environments/apple-silicon/geo.yaml'
    renv: "../environments/apple-silicon/r.yaml"
    gpuenv: ""
    rsubdir: "osx-64"
  linux:
    geoenv: '../environments/linux/geo.yaml'
    renv: "../environments/linux/r.yaml"
    gpuenv: '../environments/linux/stylegan.yaml'
    rsubdir: "linux-64"
    
paths:
  local:
    input:
      era5:
      imdaa:
    projdir: "/Users/alison/Documents/dphil/data/hazGAN2/projects"
  ouce:
    input:
      era5: "/soge-home/data/analysis/era5/0.28125x0.28125/hourly/"
      imdaa: "/soge-home/data/analysis/imdaa/"
    projdir: "/soge-home/users/spet5107/code/hazGAN2/projects/"
  arc:
    input:
      era5:
      imdaa:
    projdir: "/soge-home/users/spet5107/code/hazGAN2/projects/"