# Global config file
project: "test"

# year range
year0: 1940
yearn: 2023

# geographical boundaries
longitude:
  min: 80.0
  max: 95.0
latitude:
  min: 10.0
  max: 25.0

# fields
fields:
  u10: "max"
  v10: "max"
  msl: "min"
  tp: "sum"

field_names:
  u10: "10m_u_component_of_wind"
  v10: "10m_v_component_of_wind"
  msl: "mean_sea_level_pressure"
  tp: "total_precipitation"

# setup based-on profile
environments:
  local:
    era5dir: '/Users/alison/Documents/DPhil/data/era5'
    datadir: '/Users/alison/Documents/DPhil/data'
    environment: 'environments/local.yaml'
  cluster:
    era5dir: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    datadir: '/soge-home/projects/mistral/alison/data/'
    environment: 'environments/linux.yaml'