# Global config file
project: "bayofbengal"

# setup based-on profile
environments:
  local:
    era5dir: '/Users/alison/Documents/DPhil/data/era5'
    datadir: '/Users/alison/Documents/DPhil/data'
    environment: 'environments/local.yaml'
  cluster:
    era5dir: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    datadir: '/soge-home/projects/mistral/alison/data/'
    environment: 'environments/linux.yaml'