dataset: era5
year0: 2004 # 1941
yearn: 2018 # 2023
longitude: # geographical boundaries (15.75째 x 15.75째) (-10.875째 to 4.875째) 
  min: -10.875
  max: 4.875
latitude:
  min: 49.25
  max: 65.0
exclude:
resolution:
  lon: 64
  lat: 64
sfunc: additive 
rfunc:
  args:
  func: NULL
event_subset:
marginal_threshold: 0.95
domain: gumbel
kimg: 300
fields:
  vx:
    init:
      func: identity
      args: [i10fg]
    hfunc:
      func: max
      args: [vx]
    obj: max
    distn: weibull
    title: "Maximum wind gust"
  dx:
    init:
      func: direction
      args: [u10, v10]
    hfunc:
      func: arg2max
      args: [dx, vx]
    obj: max
    distn: truncated_gaussian
    title: "Relative direction of max wind"
  r30:
    init:
      func: sum_30_days
      args: [tp]
    hfunc:
      func: mean
      args: [r30]
    obj: max
    distn: genpareto # exponential (not implemented yet)
    title: "30-day antecedant rainfall"
points_of_interest:
local_crs: 27700 # https://epsg.io/27700
rfuncs:
  - src/funcs.R
