# Global config file
project: "bayofbengal"
resources: "resources"
renv: "../environments/r.yaml"

# environment specs
setup:
  local:
    input: "/Users/alison/Documents/DPhil/data/era5"
    output: "results"
    pyenv: '../environments/apple-silicon.yaml'
    metadata:
      description: "Analysis on Apple Silicon M2"
  cluster:
    input: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    output: 'results'
    pyenv: '../environments/linux.yaml'
    metadata:
      institution: "Oxford School of Geography and the Environment"
      description: "Analysis on departmental cluster"