# Global config file
project: "caribbeanrisk"
resources: "resources"

# environment specs
setup:
  local:
    input: "/Users/alison/Documents/DPhil/data/era5"
    output: "results"
    pyenv: '../environments/apple-silicon.yaml'
    renv: "../environments/r-silicon.yaml"
    rsubdir: "osx-64"
    metadata:
      description: "Analysis on Apple Silicon M2"
  cluster:
    input: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    output: 'results'
    pyenv: '../environments/linux.yaml'
    renv: "../environments/r-linux.yaml"
    rsubdir: "linux-64"
    metadata:
      institution: "Oxford School of Geography and the Environment"
      description: "Analysis on departmental cluster"
  slurm:
    input: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    output: 'results'
    pyenv: '../environments/linux.yaml'
    renv: "../environments/r-linux.yaml"
    rsubdir: "linux-64"
    metadata:
      institution: "Oxford School of Geography and the Environment"
      description: "Analysis on departmental cluster"