# Global config file
project: prototype
resources: "resources"
conda-cleanup-envs: true
conda-cleanup-pkgs: cache

# environment specs
setup:
  local:
    input: "/Users/alison/Documents/DPhil/data/era5"
    output: "results"
    geoenv: '../environments/apple-silicon/geo.yaml'
    renv: "../environments/apple-silicon/r.yaml"
    gpuenv: ""
    rsubdir: "osx-64"
    timecol: "valid_time"
    metadata:
      description: "Analysis on Apple Silicon M2"
  cluster:
    input: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    output: 'results'
    geoenv: '../environments/linux/geo.yaml'
    renv: "../environments/linux/r.yaml"
    gpuenv: '../environments/stylegan-linux.yaml'
    rsubdir: "linux-64"
    timecol: 'time'
    metadata:
      institution: "Oxford School of Geography and the Environment"
      description: "Analysis on departmental cluster"
  slurm:
    input: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
    output: 'results'
    geoenv: '../environments/linux/geo.yaml'
    renv: "../environments/linux/r.yaml"
    gpuenv: '../environments/stylegan-linux.yaml'
    rsubdir: "linux-64"
    timecol: "time"
    metadata:
      institution: "Oxford School of Gography and the Environment"
      description: "Analysis on departmental cluster"
