era5dir: '/soge-home/data/analysis/era5/0.28125x0.28125/hourly/'
datadir: '/soge-home/projects/mistral/alison/data/'

metadata:
  institution: "Oxford School of Geography and the Environment"
  description: "Analysis on departmental cluster"