config: ["device=cluster"]
use-conda: true
rerun-incomplete: true
jobs: 20 # number of rules to run in parallel

# if sacct enabled
executor: slurm
slurm-logdir: sbatch_dump
slurm-delete-logfiles-older-than: 1
slurm-no-account: true
default-resources:
    slurm_partition: "Short"
    mem: "16G"
    runtime: "4h"

# # here only rules, which require different (more) resources:
set-resources:
    extract_events:
        cpus_per_task: 32
        runtime: "2h"
    fit_marginals:
        slurm_partition: "Medium"
        cpus_per_task: 32
        mem_mb_per_cpu: 1G
        runtime: "4h"
    train_stylegan:
        slurm_extra: "'--gpus=1'"
        cpus_per_task: 8
        mem: "32G"
        slurm_partition: "GPU"
        runtime: "6h"
    generate_stylegan:
        slurm_partition: "GPU"
        runtime: "6h"
