config: ["device=cluster", "location=ouce"]
use-conda: true
rerun-incomplete: true
jobs: 20 # number of rules to run in parallel
latency-wait: 60

# if sacct enabled
executor: slurm
slurm-logdir: sbatch_dump
slurm-delete-logfiles-older-than: 1
slurm-no-account: true
default-resources:
    slurm_partition: "Short"
    mem: "16G"
    runtime: "4h"
    slurm_extra: "'--mail-type=END,FAIL --mail-user=spet5107@ox.ac.uk'"

# # here only rules, which require different (more) resources:
set-resources:
    extract_events:
        cpus_per_task: 32
        runtime: "2h"
    fit_marginals:
        slurm_partition: "Medium"
        cpus_per_task: 32
        mem_mb_per_cpu: 1G
        runtime: "4h"
    train_stylegan:
        slurm_partition: "GPU"
        slurm_extra: "'--gpus=1'"
        cpus_per_task: 8
        mem: "32G"
        runtime: "10h"
    generate_stylegan:
        slurm_partition: "GPU"
        slurm_extra: "'--gpus=1'"
        cpus_per_task: 8
        mem: "32G"
        runtime: "6h"
