config: ["device=cluster"]
use-conda: true
rerun-incomplete: true
jobs: 1 # number of rules to run in parallel
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition=Long
    --mem=16G
    --time=08:00:00
    --cpus-per-task=4
    --output=sbatch_dump/%j.out
    --error=sbatch_dump/%j.err

# if sacct enabled
# executor: slurm
# default-resources:
#     slurm_no_account: true # add manuall --slurm-no-account
#     slurm_partition: "Short"
#     mem_mb_per_cpu: 1800 
#     runtime: "30m"


# https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html
# https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#specifying-account-and-partition
# https://stackoverflow.com/questions/77929511/how-to-run-snakemake-8-on-a-slurm-cluster
