config: ["environment=cluster"]

# https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html
jobs: 1 # modify later
default-resources:
    slurm_account: "spet5107"
    slurm_partition: "Short"
    mem_mb_per_cpu: 1800 
    runtime: "30m"