dataset: era5
year0: 2004
yearn: 2019
nyears: 500 # to simulate
kimg: 300
antecedent_buffer_days: 30
longitude: # geographical boundaries (15.75째 x 15.75째) (-10.875째 to 4.875째) 
  min: -10.875
  max: 5.125
latitude:
  min: 49.0
  max: 64.75
exclude:
resolution:
  lon: 64
  lat: 64
sfunc: winter # [spring, summer, autumn, winter, additive]
rfunc:
  args:
  func: dummy
  desc: using custom func defined in src/funcs.R
rfuncs_dir: src/funcs.R
event_subset:
  do: True
  args: [vx]
  func: max
  value: 20
marginal_threshold: 0.95
domain: laplace
fields:
  vx:
    init:
      func: identity
      args: [i10fg]
    hfunc:
      func: max
      args: [vx]
    resample:
      func: max
    obj: max
    distn: weibull
    two_tailed: False
    title: "Maximum 10 m gust speed"
    units: "m/s"
    cmap: "cmocean.cm.speed"
  dx:
    init:
      func: dir_at_max_gust
      args: [v10, u10, i10fg]
    hfunc:
      func: arg2max
      args: [dx, vx]
    resample:
      func: mean
    obj: max
    distn: genpareto
    two_tailed: True
    title: "Direction at time of maximum 10 m gust speed"
    units: "m/s"
    cmap: "cmocean.cm.speed"
  r30:
    init:
      func: sum_30_days
      args: [tp]
    hfunc:
      func: first
      args: [r30]
    resample:
      func: average
    obj: max
    distn: genpareto
    two_tailed: False
    title: "30-day antecedant rainfall"
    units: "m"
    cmap: "cmocean.cm.rain"
points_of_interest:
  birmingham:
    lon: -1.9
    lat: 52.5
  cardiff:
    lon: -3.2
    lat: 51.5
  truro:
    lon: -5.1
    lat: 50.5
local_crs: 27700 # https://epsg.io/27700
